import type { BuildFacturXXmlInput } from "@/lib/invoice/facturx/types"

export const input: BuildFacturXXmlInput = {
  invoice: {
    number: "FAC-2026-0042",
    status: "issued",
    documentType: "invoice",
    originalInvoiceId: null,
    creditReason: null,
    currencyCode: "EUR",
    issueDate: "2026-10-09",
    dueDate: "2026-11-08",
    serviceDate: "2026-10-08",
    customerName: "Garage Martin SAS",
    customerEmail: "compta@garage-martin.example",
    customerAddress: "12 rue des Lilas, 74000 Annecy",
    customerType: "business",
    customerCountry: "FR",
    customerLegalRegistrationNumber: "98765432100011",
    customerLegalRegistrationScheme: "FR_SIRET",
    customerVatNumber: "FR98987654321",
    customerComment: null,
    issuerName: "Detailing Pro SARL",
    issuerEmail: "contact@detailing-pro.example",
    issuerAddress: "5 avenue du Lac, 74000 Annecy",
    issuerIban: "FR7630006000011234567890189",
    issuerBic: "AGRIFRPP",
    issuerCountry: "FR",
    issuerLegalRegistrationNumber: "12345678900012",
    issuerLegalRegistrationScheme: "FR_SIRET",
    issuerVatNumber: "FR12123456789",
    vatEnabled: true,
    vatRate: "20",
    taxTreatment: "STANDARD",
    taxLegalMention: null,
    itemsTotalCents: 15000,
    discountCents: 0,
    netCents: 15000,
    vatCents: 3000,
    totalCents: 18000,
    depositCents: 3000,
    paidCents: 0,
    balanceCents: 15000,
  },
  items: [
    {
      kind: "service",
      label: "Lavage intérieur complet",
      description: "Aspiration + shampoing sièges",
      quantity: 1,
      unitPriceCents: 10000,
      sortOrder: 0,
    },
    {
      kind: "option",
      label: "Traitement plastiques",
      description: null,
      quantity: 2,
      unitPriceCents: 2500,
      sortOrder: 1,
    },
  ],
}
